#!/usr/bin/env bash                                                                                 

# Disable terminal resume
defaults write com.apple.Terminal NSQuitAlwaysKeepsWindows -bool false

