version: "1"
aliases:
    cr: pr create
    co: pr checkout
    search-all: search prs --author @me
    search-merged: search prs --merged --author @me
    pr list-open: pr list --author "@me"
    pr list-merged: pr list --state merged --author "@me"
    get-release-tag: |
        !f() {
            local hash=$(gh pr view "$1" --json mergeCommit --jq '.mergeCommit.oid')

            if [ -n "$hash" ] && [ "$hash" != "null" ]; then
                git ls-remote --tags origin | grep "$COMMIT" | sed 's|.*refs/tags/||'
            else
                echo "PR $1 is unmerged or has no merge commit."
            fi
        }; f "$@"
